"""initial schema

The tables the app has always had, plus the corrections that came with moving
the schema into SQLAlchemy: `sessions.title` (in the model, never in the
database), and NOT NULL + defaults on every column backing a non-Optional
model field, which used to hand pydantic a None it refuses.

There is deliberately no `vectors` table. pgvector collections are created per
chat at runtime, with a width the app does not know until an embedding model is
picked, so PostgresVectorRepository owns that DDL — see vector_repository.py.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-23

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The vector type has to exist before PostgresVectorRepository can create
    # its first collection. Nothing below uses it, but this is the one place
    # that runs exactly once against a fresh database.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('asset_id', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('file_bytes', sa.LargeBinary(), server_default=sa.text("'\\x'::bytea"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id'),
    if_not_exists=True)
    op.create_index('idx_assets_project_id', 'assets', ['project_id', 'created_at'], unique=False,
    if_not_exists=True)
    op.create_table('chats',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('chat_id', sa.String(length=200), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('lang', sa.String(length=8), server_default='en', nullable=False),
    sa.Column('generation_model', sa.String(length=200), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('overlap_size', sa.Integer(), nullable=True),
    sa.Column('web_search', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('excluded_assets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('has_documents', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id'),
    if_not_exists=True)
    op.create_index('idx_chats_session_id', 'chats', ['session_id', 'created_at'], unique=False,
    if_not_exists=True)
    op.create_index('idx_chats_user_id', 'chats', ['user_id', 'created_at'], unique=False,
    if_not_exists=True)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('project_id', sa.String(length=24), nullable=False),
    sa.Column('asset_id', sa.String(length=200), nullable=True),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_content', sa.Text(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True)
    op.create_index('idx_chunks_project_asset', 'chunks', ['project_id', 'asset_id'], unique=False,
    if_not_exists=True)
    op.create_index('idx_chunks_project_asset_order', 'chunks', ['project_id', 'asset_id', 'chunk_order'], unique=False,
    if_not_exists=True)
    op.create_index('idx_chunks_project_id', 'chunks', ['project_id', 'created_at'], unique=False,
    if_not_exists=True)
    op.create_table('messages',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('message_id', sa.String(length=200), nullable=False),
    sa.Column('chat_id', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id'),
    if_not_exists=True)
    op.create_index('idx_messages_chat_id', 'messages', ['chat_id', 'created_at'], unique=False,
    if_not_exists=True)
    op.create_table('projects',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('chunks_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('assets_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id'),
    if_not_exists=True)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), server_default='New session', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id'),
    if_not_exists=True)
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id', 'created_at'], unique=False,
    if_not_exists=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=200), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index('idx_sessions_user_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('projects')
    op.drop_index('idx_messages_chat_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_chunks_project_id', table_name='chunks')
    op.drop_index('idx_chunks_project_asset_order', table_name='chunks')
    op.drop_index('idx_chunks_project_asset', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('idx_chats_user_id', table_name='chats')
    op.drop_index('idx_chats_session_id', table_name='chats')
    op.drop_table('chats')
    op.drop_index('idx_assets_project_id', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###

    # The extension is left in place: dropping it would take every vec_* table
    # with it, and those are not this migration's to remove.
