from . import metrics
from .config import Settings, get_settings
from .logging_config import (
    get_logger,
    new_request_id,
    request_id_ctx,
    setup_logging,
)
from .model_capabilities import (
    COMPLETION,
    EMBEDDING,
    can,
    is_safety_model,
    looks_like_embedding,
    parameters_of,
)
from .model_ids import (
    ANTHROPIC,
    CLOUD,
    GOOGLE,
    LOCAL,
    NVIDIA,
    OLLAMA_SOURCES,
    OPENROUTER,
    SOURCES,
    backend_for,
    default_chat_model,
    default_embedding_model,
    host_for,
    qualify,
    source_of,
    split_source,
)
from .provider_errors import (
    rate_limited,
    reached_generation,
    unavailable_reason,
)
from .resources import (
    available_memory_mb,
    cgroup_quota_cores,
    cpu_count,
    is_daemonic,
)

__all__ = [
    "metrics",
    "get_settings",
    "Settings",
    "backend_for",
    "ANTHROPIC",
    "GOOGLE",
    "default_chat_model",
    "default_embedding_model",
    "source_of",
    "CLOUD",
    "LOCAL",
    "NVIDIA",
    "OPENROUTER",
    "OLLAMA_SOURCES",
    "SOURCES",
    "host_for",
    "qualify",
    "split_source",
    "get_logger",
    "new_request_id",
    "request_id_ctx",
    "setup_logging",
    "COMPLETION",
    "EMBEDDING",
    "can",
    "is_safety_model",
    "looks_like_embedding",
    "parameters_of",
    "rate_limited",
    "reached_generation",
    "unavailable_reason",
    "available_memory_mb",
    "cgroup_quota_cores",
    "cpu_count",
    "is_daemonic",
]
